name: Deploy Docs

on:
  push:
    branches: main
    paths: "docs/**"
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    name: Deploy docs to gh pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: docs/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: yorunning/docs
          branch: gh-pages
          folder: docs/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
