name: Deploy Memo

on:
  push:
    branches: main
    paths: "memo/**"
  workflow_dispatch:

jobs:
  deploy-gh-pages:
    name: Deploy memo to gh pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: memo
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: memo/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          repository-name: yorunning/memo
          branch: gh-pages
          folder: memo/src/.vuepress/dist
          token: ${{ secrets.ACCESS_TOKEN }}
          single-commit: true
